# Generated by Django 3.0.5 on 2020-05-02 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('officeCode', models.IntegerField(primary_key=True, serialize=False)),
                ('officeName', models.CharField(max_length=20)),
                ('attribution', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('organizationCode', models.IntegerField(primary_key=True, serialize=False)),
                ('organizationName', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('dateJoined', models.DateField()),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceCode', models.IntegerField(primary_key=True, serialize=False)),
                ('serviceName', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=20)),
                ('premium', models.CharField(max_length=20)),
                ('allocation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('subscriberID', models.IntegerField(primary_key=True, serialize=False)),
                ('requestDate', models.DateField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('motifOfCancellation', models.TextField()),
                ('serviceCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerd.Service')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('subscriptionTypeCode', models.IntegerField(primary_key=True, serialize=False)),
                ('subscriptionTypeName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('middleName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('address1', models.CharField(max_length=20)),
                ('address2', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=10)),
                ('employerName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('transferID', models.IntegerField(primary_key=True, serialize=False)),
                ('transferFrom', models.CharField(max_length=20)),
                ('transferTo', models.CharField(max_length=20)),
                ('requestDate', models.DateField()),
                ('transferDate', models.DateField()),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerd.Subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriptionTypeCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerd.SubscriptionType'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerd.UserInfo'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(max_length=20)),
                ('endDate', models.DateField(max_length=20)),
                ('nativeCountry', models.CharField(max_length=20)),
                ('citizenship', models.CharField(max_length=20)),
                ('isDelegate', models.BooleanField()),
                ('organizationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerd.Organization')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerd.Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('officeCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerd.Office')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synerd.Subscriber')),
            ],
        ),
    ]
